import React from 'react'

export default class ColourList extends React.Component{
    constructor(props){
        super(props);
        this.state = {
            colors : [
            {"text":"Absolute Zero","hex":"#0048BA"},
            {"text":"Acid green","hex":"#B0BF1A"},
            {"text":"Aero","hex":"#7CB9E8"},
            {"text":"Aero blue","hex":"#C9FFE5"},
            {"text":"African violet","hex":"#B284BE"},
            {"text":"Air superiority blue","hex":"#72A0C1"},
            {"text":"Alabaster","hex":"#EDEAE0"},
            {"text":"Alice blue","hex":"#F0F8FF"},
            {"text":"Alloy orange","hex":"#C46210"},
            {"text":"Almond","hex":"#EFDECD"},
            {"text":"Amaranth","hex":"#E52B50"},
            {"text":"Amaranth (M&P)","hex":"#9F2B68"},
            {"text":"Amaranth pink","hex":"#F19CBB"},
            {"text":"Amaranth purple","hex":"#AB274F"},
            {"text":"Amaranth red","hex":"#D3212D"},
            {"text":"Amazon","hex":"#3B7A57"},
            {"text":"Amber","hex":"#FFBF00"},
            {"text":"Amber (SAE/ECE)","hex":"#FF7E00"},
            {"text":"Amethyst","hex":"#9966CC"},
            {"text":"Android green","hex":"#A4C639"},
            {"text":"Antique brass","hex":"#CD9575"},
            {"text":"Antique bronze","hex":"#665D1E"},
            {"text":"Antique fuchsia","hex":"#915C83"},
            {"text":"Antique ruby","hex":"#841B2D"},
            {"text":"Antique white","hex":"#FAEBD7"},
            {"text":"Ao (English)","hex":"#008000"},
            {"text":"Apple green","hex":"#8DB600"},
            {"text":"Apricot","hex":"#FBCEB1"},
            {"text":"Aqua","hex":"#00FFFF"},
            {"text":"Aquamarine","hex":"#7FFFD4"},
            {"text":"Arctic lime","hex":"#D0FF14"},
            {"text":"Army green","hex":"#4B5320"},
            {"text":"Artichoke","hex":"#8F9779"},
            {"text":"Arylide yellow","hex":"#E9D66B"},
            {"text":"Ash gray","hex":"#B2BEB5"},
            {"text":"Asparagus","hex":"#87A96B"},
            {"text":"Atomic tangerine","hex":"#FF9966"},
            {"text":"Auburn","hex":"#A52A2A"},
            {"text":"Aureolin","hex":"#FDEE00"},
            {"text":"Avocado","hex":"#568203"},
            {"text":"Azure","hex":"#007FFF"},
            {"text":"Azure (X11/web color)","hex":"#F0FFFF"},
            {"text":"Baby blue","hex":"#89CFF0"},
            {"text":"Baby blue eyes","hex":"#A1CAF1"},
            {"text":"Baby pink","hex":"#F4C2C2"},
            {"text":"Baby powder","hex":"#FEFEFA"},
            {"text":"Baker-Miller pink","hex":"#FF91AF"},
            {"text":"Banana Mania","hex":"#FAE7B5"},
            {"text":"Barbie Pink","hex":"#DA1884"},
            {"text":"Barn red","hex":"#7C0A02"},
            {"text":"Battleship grey","hex":"#848482"},
            {"text":"Beau blue","hex":"#BCD4E6"},
            {"text":"Beaver","hex":"#9F8170"},
            {"text":"Beige","hex":"#F5F5DC"},
            {"text":"B'dazzled blue","hex":"#2E5894"},
            {"text":"Big dip o’ruby","hex":"#9C2542"},
            {"text":"Bisque","hex":"#FFE4C4"},
            {"text":"Bistre","hex":"#3D2B1F"},
            {"text":"Bistre brown","hex":"#967117"},
            {"text":"Bitter lemon","hex":"#CAE00D"},
            {"text":"Bitter lime","hex":"#BFFF00"},
            {"text":"Bittersweet","hex":"#FE6F5E"},
            {"text":"Bittersweet shimmer","hex":"#BF4F51"},
            {"text":"Black","hex":"#000000"},
            {"text":"Black bean","hex":"#3D0C02"},
            {"text":"Black chocolate","hex":"#1B1811"},
            {"text":"Black coffee","hex":"#3B2F2F"},
            {"text":"Black coral","hex":"#54626F"},
            {"text":"Black olive","hex":"#3B3C36"},
            {"text":"Black Shadows","hex":"#BFAFB2"},
            {"text":"Blanched almond","hex":"#FFEBCD"},
            {"text":"Blast-off bronze","hex":"#A57164"},
            {"text":"Bleu de France","hex":"#318CE7"},
            {"text":"Blizzard blue","hex":"#ACE5EE"},
            {"text":"Blond","hex":"#FAF0BE"},
            {"text":"Blood red","hex":"#660000"},
            {"text":"Blue","hex":"#0000FF"},
            {"text":"Blue (Crayola)","hex":"#1F75FE"},
            {"text":"Blue (Munsell)","hex":"#0093AF"},
            {"text":"Blue (NCS)","hex":"#0087BD"},
            {"text":"Blue (Pantone)","hex":"#0018A8"},
            {"text":"Blue (pigment)","hex":"#333399"},
            {"text":"Blue (RYB)","hex":"#0247FE"},
            {"text":"Blue bell","hex":"#A2A2D0"},
            {"text":"Blue-gray","hex":"#6699CC"},
            {"text":"Blue-green","hex":"#0D98BA"},
            {"text":"Blue-green (color wheel)","hex":"#064E40"},
            {"text":"Blue jeans","hex":"#5DADEC"},
            {"text":"Blue sapphire","hex":"#126180"},
            {"text":"Blue-violet","hex":"#8A2BE2"},
            {"text":"Blue-violet (Crayola)","hex":"#7366BD"},
            {"text":"Blue-violet (color wheel)","hex":"#4D1A7F"},
            {"text":"Blue yonder","hex":"#5072A7"},
            {"text":"Bluetiful","hex":"#3C69E7"},
            {"text":"Blush","hex":"#DE5D83"},
            {"text":"Bole","hex":"#79443B"},
            {"text":"Bone","hex":"#E3DAC9"},
            {"text":"Bottle green","hex":"#006A4E"},
            {"text":"Brandy","hex":"#87413F"},
            {"text":"Brick red","hex":"#CB4154"},
            {"text":"Bright green","hex":"#66FF00"},
            {"text":"Bright lilac","hex":"#D891EF"},
            {"text":"Bright maroon","hex":"#C32148"},
            {"text":"Bright navy blue","hex":"#1974D2"},
            {"text":"Bright yellow (Crayola)","hex":"#FFAA1D"},
            {"text":"Brilliant rose","hex":"#FF55A3"},
            {"text":"Brink pink","hex":"#FB607F"},
            {"text":"British racing green","hex":"#004225"},
            {"text":"Bronze","hex":"#CD7F32"},
            {"text":"Brown","hex":"#88540B"},
            {"text":"Brown sugar","hex":"#AF6E4D"},
            {"text":"Brunswick green","hex":"#1B4D3E"},
            {"text":"Bud green","hex":"#7BB661"},
            {"text":"Buff","hex":"#F0DC82"},
            {"text":"Burgundy","hex":"#800020"},
            {"text":"Burlywood","hex":"#DEB887"},
            {"text":"Burnished brown","hex":"#A17A74"},
            {"text":"Burnt orange","hex":"#CC5500"},
            {"text":"Burnt sienna","hex":"#E97451"},
            {"text":"Burnt umber","hex":"#8A3324"},
            {"text":"Byzantine","hex":"#BD33A4"},
            {"text":"Byzantium","hex":"#702963"},
            {"text":"Cadet","hex":"#536872"},
            {"text":"Cadet blue","hex":"#5F9EA0"},
            {"text":"Cadet blue (Crayola)","hex":"#A9B2C3"},
            {"text":"Cadet grey","hex":"#91A3B0"},
            {"text":"Cadmium green","hex":"#006B3C"},
            {"text":"Cadmium orange","hex":"#ED872D"},
            {"text":"Cadmium red","hex":"#E30022"},
            {"text":"Cadmium yellow","hex":"#FFF600"},
            {"text":"Café au lait","hex":"#A67B5B"},
            {"text":"Café noir","hex":"#4B3621"},
            {"text":"Cambridge blue","hex":"#A3C1AD"},
            {"text":"Camel","hex":"#C19A6B"},
            {"text":"Cameo pink","hex":"#EFBBCC"},
            {"text":"Canary","hex":"#FFFF99"},
            {"text":"Canary yellow","hex":"#FFEF00"},
            {"text":"Candy apple red","hex":"#FF0800"},
            {"text":"Candy pink","hex":"#E4717A"},
            {"text":"Capri","hex":"#00BFFF"},
            {"text":"Caput mortuum","hex":"#592720"},
            {"text":"Cardinal","hex":"#C41E3A"},
            {"text":"Caribbean green","hex":"#00CC99"},
            {"text":"Carmine","hex":"#960018"},
            {"text":"Carmine (M&P)","hex":"#D70040"},
            {"text":"Carnation pink","hex":"#FFA6C9"},
            {"text":"Carnelian","hex":"#B31B1B"},
            {"text":"Carolina blue","hex":"#56A0D3"},
            {"text":"Carrot orange","hex":"#ED9121"},
            {"text":"Castleton green","hex":"#00563F"},
            {"text":"Catawba","hex":"#703642"},
            {"text":"Cedar Chest","hex":"#C95A49"},
            {"text":"Celadon","hex":"#ACE1AF"},
            {"text":"Celadon blue","hex":"#007BA7"},
            {"text":"Celadon green","hex":"#2F847C"},
            {"text":"Celeste","hex":"#B2FFFF"},
            {"text":"Celtic blue","hex":"#246BCE"},
            {"text":"Cerise","hex":"#DE3163"},
            {"text":"Cerulean","hex":"#007BA7"},
            {"text":"Cerulean blue","hex":"#2A52BE"},
            {"text":"Cerulean frost","hex":"#6D9BC3"},
            {"text":"Cerulean (Crayola)","hex":"#1DACD6"},
            {"text":"CG blue","hex":"#007AA5"},
            {"text":"CG red","hex":"#E03C31"},
            {"text":"Champagne","hex":"#F7E7CE"},
            {"text":"Champagne pink","hex":"#F1DDCF"},
            {"text":"Charcoal","hex":"#36454F"},
            {"text":"Charleston green","hex":"#232B2B"},
            {"text":"Charm pink","hex":"#E68FAC"},
            {"text":"Chartreuse (traditional)","hex":"#DFFF00"},
            {"text":"Chartreuse (web)","hex":"#7FFF00"},
            {"text":"Cherry blossom pink","hex":"#FFB7C5"},
            {"text":"Chestnut","hex":"#954535"},
            {"text":"China pink","hex":"#DE6FA1"},
            {"text":"China rose","hex":"#A8516E"},
            {"text":"Chinese red","hex":"#AA381E"},
            {"text":"Chinese violet","hex":"#856088"},
            {"text":"Chinese yellow","hex":"#FFB200"},
            {"text":"Chocolate (traditional)","hex":"#7B3F00"},
            {"text":"Chocolate (web)","hex":"#D2691E"},
            {"text":"Chrome yellow","hex":"#FFA700"},
            {"text":"Cinereous","hex":"#98817B"},
            {"text":"Cinnabar","hex":"#E34234"},
            {"text":"Cinnamon Satin","hex":"#CD607E"},
            {"text":"Citrine","hex":"#E4D00A"},
            {"text":"Citron","hex":"#9FA91F"},
            {"text":"Claret","hex":"#7F1734"},
            {"text":"Cobalt blue","hex":"#0047AB"},
            {"text":"Cocoa brown","hex":"#D2691E"},
            {"text":"Coffee","hex":"#6F4E37"},
            {"text":"Columbia Blue","hex":"#B9D9EB"},
            {"text":"Congo pink","hex":"#F88379"},
            {"text":"Cool grey","hex":"#8C92AC"},
            {"text":"Copper","hex":"#B87333"},
            {"text":"Copper (Crayola)","hex":"#DA8A67"},
            {"text":"Copper penny","hex":"#AD6F69"},
            {"text":"Copper red","hex":"#CB6D51"},
            {"text":"Copper rose","hex":"#996666"},
            {"text":"Coquelicot","hex":"#FF3800"},
            {"text":"Coral","hex":"#FF7F50"},
            {"text":"Coral pink","hex":"#F88379"},
            {"text":"Cordovan","hex":"#893F45"},
            {"text":"Corn","hex":"#FBEC5D"},
            {"text":"Cornflower blue","hex":"#6495ED"},
            {"text":"Cornsilk","hex":"#FFF8DC"},
            {"text":"Cosmic cobalt","hex":"#2E2D88"},
            {"text":"Cosmic latte","hex":"#FFF8E7"},
            {"text":"Coyote brown","hex":"#81613C"},
            {"text":"Cotton candy","hex":"#FFBCD9"},
            {"text":"Cream","hex":"#FFFDD0"},
            {"text":"Crimson","hex":"#DC143C"},
            {"text":"Crimson (UA)","hex":"#9E1B32"},
            {"text":"Cultured","hex":"#F5F5F5"},
            {"text":"Cyan","hex":"#00FFFF"},
            {"text":"Cyan (process)","hex":"#00B7EB"},
            {"text":"Cyber grape","hex":"#58427C"},
            {"text":"Cyber yellow","hex":"#FFD300"},
            {"text":"Cyclamen","hex":"#F56FA1"},
            {"text":"Dark blue-gray","hex":"#666699"},
            {"text":"Dark brown","hex":"#654321"},
            {"text":"Dark byzantium","hex":"#5D3954"},
            {"text":"Dark cornflower blue","hex":"#26428B"},
            {"text":"Dark cyan","hex":"#008B8B"},
            {"text":"Dark electric blue","hex":"#536878"},
            {"text":"Dark goldenrod","hex":"#B8860B"},
            {"text":"Dark green","hex":"#013220"},
            {"text":"Dark green (X11)","hex":"#006400"},
            {"text":"Dark jungle green","hex":"#1A2421"},
            {"text":"Dark khaki","hex":"#BDB76B"},
            {"text":"Dark lava","hex":"#483C32"},
            {"text":"Dark liver","hex":"#534B4F"},
            {"text":"Dark liver (horses)","hex":"#543D37"},
            {"text":"Dark magenta","hex":"#8B008B"},
            {"text":"Dark moss green","hex":"#4A5D23"},
            {"text":"Dark olive green","hex":"#556B2F"},
            {"text":"Dark orange","hex":"#FF8C00"},
            {"text":"Dark orchid","hex":"#9932CC"},
            {"text":"Dark pastel green","hex":"#03C03C"},
            {"text":"Dark purple","hex":"#301934"},
            {"text":"Dark red","hex":"#8B0000"},
            {"text":"Dark salmon","hex":"#E9967A"},
            {"text":"Dark sea green","hex":"#8FBC8F"},
            {"text":"Dark sienna","hex":"#3C1414"},
            {"text":"Dark sky blue","hex":"#8CBED6"},
            {"text":"Dark slate blue","hex":"#483D8B"},
            {"text":"Dark slate gray","hex":"#2F4F4F"},
            {"text":"Dark spring green","hex":"#177245"},
            {"text":"Dark turquoise","hex":"#00CED1"},
            {"text":"Dark violet","hex":"#9400D3"},
            {"text":"Dartmouth green","hex":"#00703C"},
            {"text":"Davy's grey","hex":"#555555"},
            {"text":"Deep cerise","hex":"#DA3287"},
            {"text":"Deep champagne","hex":"#FAD6A5"},
            {"text":"Deep chestnut","hex":"#B94E48"},
            {"text":"Deep jungle green","hex":"#004B49"},
            {"text":"Deep pink","hex":"#FF1493"},
            {"text":"Deep saffron","hex":"#FF9933"},
            {"text":"Deep sky blue","hex":"#00BFFF"},
            {"text":"Deep Space Sparkle","hex":"#4A646C"},
            {"text":"Deep taupe","hex":"#7E5E60"},
            {"text":"Denim","hex":"#1560BD"},
            {"text":"Denim blue","hex":"#2243B6"},
            {"text":"Desert","hex":"#C19A6B"},
            {"text":"Desert sand","hex":"#EDC9AF"},
            {"text":"Dim gray","hex":"#696969"},
            {"text":"Dodger blue","hex":"#1E90FF"},
            {"text":"Dogwood rose","hex":"#D71868"},
            {"text":"Drab","hex":"#967117"},
            {"text":"Duke blue","hex":"#00009C"},
            {"text":"Dutch white","hex":"#EFDFBB"},
            {"text":"Earth yellow","hex":"#E1A95F"},
            {"text":"Ebony","hex":"#555D50"},
            {"text":"Ecru","hex":"#C2B280"},
            {"text":"Eerie black","hex":"#1B1B1B"},
            {"text":"Eggplant","hex":"#614051"},
            {"text":"Eggshell","hex":"#F0EAD6"},
            {"text":"Egyptian blue","hex":"#1034A6"},
            {"text":"Electric blue","hex":"#7DF9FF"},
            {"text":"Electric green","hex":"#00FF00"},
            {"text":"Electric indigo","hex":"#6F00FF"},
            {"text":"Electric lime","hex":"#CCFF00"},
            {"text":"Electric purple","hex":"#BF00FF"},
            {"text":"Electric violet","hex":"#8F00FF"},
            {"text":"Emerald","hex":"#50C878"},
            {"text":"Eminence","hex":"#6C3082"},
            {"text":"English green","hex":"#1B4D3E"},
            {"text":"English lavender","hex":"#B48395"},
            {"text":"English red","hex":"#AB4B52"},
            {"text":"English vermillion","hex":"#CC474B"},
            {"text":"English violet","hex":"#563C5C"},
            {"text":"Erin","hex":"#00FF40"},
            {"text":"Eton blue","hex":"#96C8A2"},
            {"text":"Fallow","hex":"#C19A6B"},
            {"text":"Falu red","hex":"#801818"},
            {"text":"Fandango","hex":"#B53389"},
            {"text":"Fandango pink","hex":"#DE5285"},
            {"text":"Fashion fuchsia","hex":"#F400A1"},
            {"text":"Fawn","hex":"#E5AA70"},
            {"text":"Feldgrau","hex":"#4D5D53"},
            {"text":"Fern green","hex":"#4F7942"},
            {"text":"Field drab","hex":"#6C541E"},
            {"text":"Fiery rose","hex":"#FF5470"},
            {"text":"Firebrick","hex":"#B22222"},
            {"text":"Fire engine red","hex":"#CE2029"},
            {"text":"Fire opal","hex":"#E95C4B"},
            {"text":"Flame","hex":"#E25822"},
            {"text":"Flax","hex":"#EEDC82"},
            {"text":"Flickr Blue","hex":"#0063dc"},
            {"text":"Flickr Pink","hex":"#FB0081"},
            {"text":"Flirt","hex":"#A2006D"},
            {"text":"Floral white","hex":"#FFFAF0"},
            {"text":"Fluorescent blue","hex":"#15F4EE"},
            {"text":"Forest green (Crayola)","hex":"#5FA777"},
            {"text":"Forest green (traditional)","hex":"#014421"},
            {"text":"Forest green (web)","hex":"#228B22"},
            {"text":"French beige","hex":"#A67B5B"},
            {"text":"French bistre","hex":"#856D4D"},
            {"text":"French blue","hex":"#0072BB"},
            {"text":"French fuchsia","hex":"#FD3F92"},
            {"text":"French lilac","hex":"#86608E"},
            {"text":"French lime","hex":"#9EFD38"},
            {"text":"French mauve","hex":"#D473D4"},
            {"text":"French pink","hex":"#FD6C9E"},
            {"text":"French raspberry","hex":"#C72C48"},
            {"text":"French rose","hex":"#F64A8A"},
            {"text":"French sky blue","hex":"#77B5FE"},
            {"text":"French violet","hex":"#8806CE"},
            {"text":"Frostbite","hex":"#E936A7"},
            {"text":"Fuchsia","hex":"#FF00FF"},
            {"text":"Fuchsia (Crayola)","hex":"#C154C1"},
            {"text":"Fuchsia purple","hex":"#CC397B"},
            {"text":"Fuchsia rose","hex":"#C74375"},
            {"text":"Fulvous","hex":"#E48400"},
            {"text":"Fuzzy Wuzzy","hex":"#CC6666"},
            {"text":"Gainsboro","hex":"#DCDCDC"},
            {"text":"Gamboge","hex":"#E49B0F"},
            {"text":"Generic viridian","hex":"#007F66"},
            {"text":"Ghost white","hex":"#F8F8FF"},
            {"text":"Glaucous","hex":"#6082B6"},
            {"text":"Glossy grape","hex":"#AB92B3"},
            {"text":"GO green","hex":"#00AB66"},
            {"text":"Gold","hex":"#A57C00"},
            {"text":"Gold (metallic)","hex":"#D4AF37"},
            {"text":"Gold (web) (Golden)","hex":"#FFD700"},
            {"text":"Gold (Crayola)","hex":"#E6BE8A"},
            {"text":"Gold Fusion","hex":"#85754E"},
            {"text":"Golden brown","hex":"#996515"},
            {"text":"Golden poppy","hex":"#FCC200"},
            {"text":"Golden yellow","hex":"#FFDF00"},
            {"text":"Goldenrod","hex":"#DAA520"},
            {"text":"Granite gray","hex":"#676767"},
            {"text":"Granny Smith apple","hex":"#A8E4A0"},
            {"text":"Gray (web)","hex":"#808080"},
            {"text":"Gray (X11 gray)","hex":"#BEBEBE"},
            {"text":"Green","hex":"#00FF00"},
            {"text":"Green (Crayola)","hex":"#1CAC78"},
            {"text":"Green (web)","hex":"#008000"},
            {"text":"Green (Munsell)","hex":"#00A877"},
            {"text":"Green (NCS)","hex":"#009F6B"},
            {"text":"Green (Pantone)","hex":"#00AD43"},
            {"text":"Green (pigment)","hex":"#00A550"},
            {"text":"Green (RYB)","hex":"#66B032"},
            {"text":"Green-blue","hex":"#1164B4"},
            {"text":"Green-blue (Crayola)","hex":"#2887C8"},
            {"text":"Green-cyan","hex":"#009966"},
            {"text":"Green Lizard","hex":"#A7F432"},
            {"text":"Green Sheen","hex":"#6EAEA1"},
            {"text":"Green-yellow","hex":"#ADFF2F"},
            {"text":"Green-yellow (Crayola)","hex":"#F0E891"},
            {"text":"Grullo","hex":"#A99A86"},
            {"text":"Gunmetal","hex":"#2a3439"},
            {"text":"Han blue","hex":"#446CCF"},
            {"text":"Han purple","hex":"#5218FA"},
            {"text":"Hansa yellow","hex":"#E9D66B"},
            {"text":"Harlequin","hex":"#3FFF00"},
            {"text":"Harvest gold","hex":"#DA9100"},
            {"text":"Heat Wave","hex":"#FF7A00"},
            {"text":"Heliotrope","hex":"#DF73FF"},
            {"text":"Heliotrope gray","hex":"#AA98A9"},
            {"text":"Hollywood cerise","hex":"#F400A1"},
            {"text":"Honeydew","hex":"#F0FFF0"},
            {"text":"Honolulu blue","hex":"#006DB0"},
            {"text":"Hooker's green","hex":"#49796B"},
            {"text":"Hot magenta","hex":"#FF1DCE"},
            {"text":"Hot pink","hex":"#FF69B4"},
            {"text":"Hunter green","hex":"#355E3B"},
            {"text":"Iceberg","hex":"#71A6D2"},
            {"text":"Icterine","hex":"#FCF75E"},
            {"text":"Illuminating emerald","hex":"#319177"},
            {"text":"Imperial red","hex":"#ED2939"},
            {"text":"Inchworm","hex":"#B2EC5D"},
            {"text":"Independence","hex":"#4C516D"},
            {"text":"India green","hex":"#138808"},
            {"text":"Indian red","hex":"#CD5C5C"},
            {"text":"Indian yellow","hex":"#E3A857"},
            {"text":"Indigo","hex":"#4B0082"},
            {"text":"Indigo dye","hex":"#00416A"},
            {"text":"International Klein Blue","hex":"#002FA7"},
            {"text":"International orange (aerospace)","hex":"#FF4F00"},
            {"text":"International orange (engineering)","hex":"#BA160C"},
            {"text":"International orange (Golden Gate Bridge)","hex":"#C0362C"},
            {"text":"Iris","hex":"#5A4FCF"},
            {"text":"Irresistible","hex":"#B3446C"},
            {"text":"Isabelline","hex":"#F4F0EC"},
            {"text":"Italian sky blue","hex":"#B2FFFF"},
            {"text":"Ivory","hex":"#FFFFF0"},
            {"text":"Jade","hex":"#00A86B"},
            {"text":"Jasmine","hex":"#F8DE7E"},
            {"text":"Jazzberry jam","hex":"#A50B5E"},
            {"text":"Jet","hex":"#343434"},
            {"text":"Jonquil","hex":"#F4CA16"},
            {"text":"June bud","hex":"#BDDA57"},
            {"text":"Jungle green","hex":"#29AB87"},
            {"text":"Kelly green","hex":"#4CBB17"},
            {"text":"Keppel","hex":"#3AB09E"},
            {"text":"Key lime","hex":"#E8F48C"},
            {"text":"Khaki (web)","hex":"#C3B091"},
            {"text":"Khaki (X11) (Light khaki)","hex":"#F0E68C"},
            {"text":"Kobe","hex":"#882D17"},
            {"text":"Kobi","hex":"#E79FC4"},
            {"text":"Kobicha","hex":"#6B4423"},
            {"text":"Kombu green","hex":"#354230"},
            {"text":"KSU purple","hex":"#512888"},
            {"text":"Languid lavender","hex":"#D6CADD"},
            {"text":"Lapis lazuli","hex":"#26619C"},
            {"text":"Laser lemon","hex":"#FFFF66"},
            {"text":"Laurel green","hex":"#A9BA9D"},
            {"text":"Lava","hex":"#CF1020"},
            {"text":"Lavender (floral)","hex":"#B57EDC"},
            {"text":"Lavender (web)","hex":"#E6E6FA"},
            {"text":"Lavender blue","hex":"#CCCCFF"},
            {"text":"Lavender blush","hex":"#FFF0F5"},
            {"text":"Lavender gray","hex":"#C4C3D0"},
            {"text":"Lawn green","hex":"#7CFC00"},
            {"text":"Lemon","hex":"#FFF700"},
            {"text":"Lemon chiffon","hex":"#FFFACD"},
            {"text":"Lemon curry","hex":"#CCA01D"},
            {"text":"Lemon glacier","hex":"#FDFF00"},
            {"text":"Lemon meringue","hex":"#F6EABE"},
            {"text":"Lemon yellow","hex":"#FFF44F"},
            {"text":"Lemon yellow (Crayola)","hex":"#FFFF9F"},
            {"text":"Liberty","hex":"#545AA7"},
            {"text":"Light blue","hex":"#ADD8E6"},
            {"text":"Light coral","hex":"#F08080"},
            {"text":"Light cornflower blue","hex":"#93CCEA"},
            {"text":"Light cyan","hex":"#E0FFFF"},
            {"text":"Light French beige","hex":"#C8AD7F"},
            {"text":"Light goldenrod yellow","hex":"#FAFAD2"},
            {"text":"Light gray","hex":"#D3D3D3"},
            {"text":"Light green","hex":"#90EE90"},
            {"text":"Light orange","hex":"#FED8B1"},
            {"text":"Light periwinkle","hex":"#C5CBE1"},
            {"text":"Light pink","hex":"#FFB6C1"},
            {"text":"Light salmon","hex":"#FFA07A"},
            {"text":"Light sea green","hex":"#20B2AA"},
            {"text":"Light sky blue","hex":"#87CEFA"},
            {"text":"Light slate gray","hex":"#778899"},
            {"text":"Light steel blue","hex":"#B0C4DE"},
            {"text":"Light yellow","hex":"#FFFFE0"},
            {"text":"Lilac","hex":"#C8A2C8"},
            {"text":"Lilac Luster","hex":"#AE98AA"},
            {"text":"Lime (color wheel)","hex":"#BFFF00"},
            {"text":"Lime (web) (X11 green)","hex":"#00FF00"},
            {"text":"Lime green","hex":"#32CD32"},
            {"text":"Lincoln green","hex":"#195905"},
            {"text":"Linen","hex":"#FAF0E6"},
            {"text":"Lion","hex":"#C19A6B"},
            {"text":"Liseran purple","hex":"#DE6FA1"},
            {"text":"Little boy blue","hex":"#6CA0DC"},
            {"text":"Liver","hex":"#674C47"},
            {"text":"Liver (dogs)","hex":"#B86D29"},
            {"text":"Liver (organ)","hex":"#6C2E1F"},
            {"text":"Liver chestnut","hex":"#987456"},
            {"text":"Livid","hex":"#6699CC"},
            {"text":"Macaroni and Cheese","hex":"#FFBD88"},
            {"text":"Madder Lake","hex":"#CC3336"},
            {"text":"Magenta","hex":"#FF00FF"},
            {"text":"Magenta (Crayola)","hex":"#F653A6"},
            {"text":"Magenta (dye)","hex":"#CA1F7B"},
            {"text":"Magenta (Pantone)","hex":"#D0417E"},
            {"text":"Magenta (process)","hex":"#FF0090"},
            {"text":"Magenta haze","hex":"#9F4576"},
            {"text":"Magic mint","hex":"#AAF0D1"},
            {"text":"Magnolia","hex":"#F8F4FF"},
            {"text":"Mahogany","hex":"#C04000"},
            {"text":"Maize","hex":"#FBEC5D"},
            {"text":"Maize (Crayola)","hex":"#F2C649"},
            {"text":"Majorelle blue","hex":"#6050DC"},
            {"text":"Malachite","hex":"#0BDA51"},
            {"text":"Manatee","hex":"#979AAA"},
            {"text":"Mandarin","hex":"#F37A48"},
            {"text":"Mango","hex":"#FDBE02"},
            {"text":"Mango Tango","hex":"#FF8243"},
            {"text":"Mantis","hex":"#74C365"},
            {"text":"Mardi Gras","hex":"#880085"},
            {"text":"Marigold","hex":"#EAA221"},
            {"text":"Maroon (Crayola)","hex":"#C32148"},
            {"text":"Maroon (web)","hex":"#800000"},
            {"text":"Maroon (X11)","hex":"#B03060"},
            {"text":"Mauve","hex":"#E0B0FF"},
            {"text":"Mauve taupe","hex":"#915F6D"},
            {"text":"Mauvelous","hex":"#EF98AA"},
            {"text":"Maximum blue","hex":"#47ABCC"},
            {"text":"Maximum blue green","hex":"#30BFBF"},
            {"text":"Maximum blue purple","hex":"#ACACE6"},
            {"text":"Maximum green","hex":"#5E8C31"},
            {"text":"Maximum green yellow","hex":"#D9E650"},
            {"text":"Maximum purple","hex":"#733380"},
            {"text":"Maximum red","hex":"#D92121"},
            {"text":"Maximum red purple","hex":"#A63A79"},
            {"text":"Maximum yellow","hex":"#FAFA37"},
            {"text":"Maximum yellow red","hex":"#F2BA49"},
            {"text":"May green","hex":"#4C9141"},
            {"text":"Maya blue","hex":"#73C2FB"},
            {"text":"Medium aquamarine","hex":"#66DDAA"},
            {"text":"Medium blue","hex":"#0000CD"},
            {"text":"Medium candy apple red","hex":"#E2062C"},
            {"text":"Medium carmine","hex":"#AF4035"},
            {"text":"Medium champagne","hex":"#F3E5AB"},
            {"text":"Medium orchid","hex":"#BA55D3"},
            {"text":"Medium purple","hex":"#9370DB"},
            {"text":"Medium sea green","hex":"#3CB371"},
            {"text":"Medium slate blue","hex":"#7B68EE"},
            {"text":"Medium spring green","hex":"#00FA9A"},
            {"text":"Medium turquoise","hex":"#48D1CC"},
            {"text":"Medium violet-red","hex":"#C71585"},
            {"text":"Mellow apricot","hex":"#F8B878"},
            {"text":"Mellow yellow","hex":"#F8DE7E"},
            {"text":"Melon","hex":"#FEBAAD"},
            {"text":"Metallic gold","hex":"#D3AF37"},
            {"text":"Metallic Seaweed","hex":"#0A7E8C"},
            {"text":"Metallic Sunburst","hex":"#9C7C38"},
            {"text":"Mexican pink","hex":"#E4007C"},
            {"text":"Middle blue","hex":"#7ED4E6"},
            {"text":"Middle blue green","hex":"#8DD9CC"},
            {"text":"Middle blue purple","hex":"#8B72BE"},
            {"text":"Middle grey","hex":"#8B8680"},
            {"text":"Middle green","hex":"#4D8C57"},
            {"text":"Middle green yellow","hex":"#ACBF60"},
            {"text":"Middle purple","hex":"#D982B5"},
            {"text":"Middle red","hex":"#E58E73"},
            {"text":"Middle red purple","hex":"#A55353"},
            {"text":"Middle yellow","hex":"#FFEB00"},
            {"text":"Middle yellow red","hex":"#ECB176"},
            {"text":"Midnight","hex":"#702670"},
            {"text":"Midnight blue","hex":"#191970"},
            {"text":"Midnight green (eagle green)","hex":"#004953"},
            {"text":"Mikado yellow","hex":"#FFC40C"},
            {"text":"Mimi pink","hex":"#FFDAE9"},
            {"text":"Mindaro","hex":"#E3F988"},
            {"text":"Ming","hex":"#36747D"},
            {"text":"Minion yellow","hex":"#F5E050"},
            {"text":"Mint","hex":"#3EB489"},
            {"text":"Mint cream","hex":"#F5FFFA"},
            {"text":"Mint green","hex":"#98FF98"},
            {"text":"Misty moss","hex":"#BBB477"},
            {"text":"Misty rose","hex":"#FFE4E1"},
            {"text":"Mode beige","hex":"#967117"},
            {"text":"Morning blue","hex":"#8DA399"},
            {"text":"Moss green","hex":"#8A9A5B"},
            {"text":"Mountain Meadow","hex":"#30BA8F"},
            {"text":"Mountbatten pink","hex":"#997A8D"},
            {"text":"MSU green","hex":"#18453B"},
            {"text":"Mulberry","hex":"#C54B8C"},
            {"text":"Mulberry (Crayola)","hex":"#C8509B"},
            {"text":"Mustard","hex":"#FFDB58"},
            {"text":"Myrtle green","hex":"#317873"},
            {"text":"Mystic","hex":"#D65282"},
            {"text":"Mystic maroon","hex":"#AD4379"},
            {"text":"Nadeshiko pink","hex":"#F6ADC6"},
            {"text":"Naples yellow","hex":"#FADA5E"},
            {"text":"Navajo white","hex":"#FFDEAD"},
            {"text":"Navy blue","hex":"#000080"},
            {"text":"Navy blue (Crayola)","hex":"#1974D2"},
            {"text":"Neon blue","hex":"#4666FF"},
            {"text":"Neon green","hex":"#39FF14"},
            {"text":"New York pink","hex":"#D7837F"},
            {"text":"Nickel","hex":"#727472"},
            {"text":"Non-photo blue","hex":"#A4DDED"},
            {"text":"Nyanza","hex":"#E9FFDB"},
            {"text":"Ocean Blue","hex":"#4F42B5"},
            {"text":"Ocean green","hex":"#48BF91"},
            {"text":"Ochre","hex":"#CC7722"},
            {"text":"Old burgundy","hex":"#43302E"},
            {"text":"Old gold","hex":"#CFB53B"},
            {"text":"Old lace","hex":"#FDF5E6"},
            {"text":"Old lavender","hex":"#796878"},
            {"text":"Old mauve","hex":"#673147"},
            {"text":"Old rose","hex":"#C08081"},
            {"text":"Old silver","hex":"#848482"},
            {"text":"Olive","hex":"#808000"},
            {"text":"Olive Drab (#3)","hex":"#6B8E23"},
            {"text":"Olive Drab #7","hex":"#3C341F"},
            {"text":"Olive green","hex":"#B5B35C"},
            {"text":"Olivine","hex":"#9AB973"},
            {"text":"Onyx","hex":"#353839"},
            {"text":"Opal","hex":"#A8C3BC"},
            {"text":"Opera mauve","hex":"#B784A7"},
            {"text":"Orange","hex":"#FF7F00"},
            {"text":"Orange (Crayola)","hex":"#FF7538"},
            {"text":"Orange (Pantone)","hex":"#FF5800"},
            {"text":"Orange (web)","hex":"#FFA500"},
            {"text":"Orange peel","hex":"#FF9F00"},
            {"text":"Orange-red","hex":"#FF681F"},
            {"text":"Orange-red (Crayola)","hex":"#FF5349"},
            {"text":"Orange soda","hex":"#FA5B3D"},
            {"text":"Orange-yellow","hex":"#F5BD1F"},
            {"text":"Orange-yellow (Crayola)","hex":"#F8D568"},
            {"text":"Orchid","hex":"#DA70D6"},
            {"text":"Orchid pink","hex":"#F2BDCD"},
            {"text":"Orchid (Crayola)","hex":"#E29CD2"},
            {"text":"Outer space (Crayola)","hex":"#2D383A"},
            {"text":"Outrageous Orange","hex":"#FF6E4A"},
            {"text":"Oxblood","hex":"#800020"},
            {"text":"Oxford blue","hex":"#002147"},
            {"text":"OU Crimson red","hex":"#841617"},
            {"text":"Pacific blue","hex":"#1CA9C9"},
            {"text":"Pakistan green","hex":"#006600"},
            {"text":"Palatinate purple","hex":"#682860"},
            {"text":"Pale aqua","hex":"#BCD4E6"},
            {"text":"Pale cerulean","hex":"#9BC4E2"},
            {"text":"Pale pink","hex":"#FADADD"},
            {"text":"Pale purple (Pantone)","hex":"#FAE6FA"},
            {"text":"Pale silver","hex":"#C9C0BB"},
            {"text":"Pale spring bud","hex":"#ECEBBD"},
            {"text":"Pansy purple","hex":"#78184A"},
            {"text":"Paolo Veronese green","hex":"#009B7D"},
            {"text":"Papaya whip","hex":"#FFEFD5"},
            {"text":"Paradise pink","hex":"#E63E62"},
            {"text":"Paris Green","hex":"#50C878"},
            {"text":"Pastel pink","hex":"#DEA5A4"},
            {"text":"Patriarch","hex":"#800080"},
            {"text":"Payne's grey","hex":"#536878"},
            {"text":"Peach","hex":"#FFE5B4"},
            {"text":"Peach (Crayola)","hex":"#FFCBA4"},
            {"text":"Peach puff","hex":"#FFDAB9"},
            {"text":"Pear","hex":"#D1E231"},
            {"text":"Pearly purple","hex":"#B768A2"},
            {"text":"Periwinkle","hex":"#CCCCFF"},
            {"text":"Periwinkle (Crayola)","hex":"#C3CDE6"},
            {"text":"Permanent Geranium Lake","hex":"#E12C2C"},
            {"text":"Persian blue","hex":"#1C39BB"},
            {"text":"Persian green","hex":"#00A693"},
            {"text":"Persian indigo","hex":"#32127A"},
            {"text":"Persian orange","hex":"#D99058"},
            {"text":"Persian pink","hex":"#F77FBE"},
            {"text":"Persian plum","hex":"#701C1C"},
            {"text":"Persian red","hex":"#CC3333"},
            {"text":"Persian rose","hex":"#FE28A2"},
            {"text":"Persimmon","hex":"#EC5800"},
            {"text":"Pewter Blue","hex":"#8BA8B7"},
            {"text":"Phlox","hex":"#DF00FF"},
            {"text":"Phthalo blue","hex":"#000F89"},
            {"text":"Phthalo green","hex":"#123524"},
            {"text":"Picotee blue","hex":"#2E2787"},
            {"text":"Pictorial carmine","hex":"#C30B4E"},
            {"text":"Piggy pink","hex":"#FDDDE6"},
            {"text":"Pine green","hex":"#01796F"},
            {"text":"Pine tree","hex":"#2A2F23"},
            {"text":"Pink","hex":"#FFC0CB"},
            {"text":"Pink (Pantone)","hex":"#D74894"},
            {"text":"Pink flamingo","hex":"#FC74FD"},
            {"text":"Pink lace","hex":"#FFDDF4"},
            {"text":"Pink lavender","hex":"#D8B2D1"},
            {"text":"Pink Sherbet","hex":"#F78FA7"},
            {"text":"Pistachio","hex":"#93C572"},
            {"text":"Platinum","hex":"#E5E4E2"},
            {"text":"Plum","hex":"#8E4585"},
            {"text":"Plum (web)","hex":"#DDA0DD"},
            {"text":"Plump Purple","hex":"#5946B2"},
            {"text":"Polished Pine","hex":"#5DA493"},
            {"text":"Pomp and Power","hex":"#86608E"},
            {"text":"Popstar","hex":"#BE4F62"},
            {"text":"Portland Orange","hex":"#FF5A36"},
            {"text":"Powder blue","hex":"#B0E0E6"},
            {"text":"Princeton orange","hex":"#F58025"},
            {"text":"Prune","hex":"#701C1C"},
            {"text":"Prussian blue","hex":"#003153"},
            {"text":"Psychedelic purple","hex":"#DF00FF"},
            {"text":"Puce","hex":"#CC8899"},
            {"text":"Pullman Brown (UPS Brown)","hex":"#644117"},
            {"text":"Pumpkin","hex":"#FF7518"},
            {"text":"Purple","hex":"#6A0DAD"},
            {"text":"Purple (web)","hex":"#800080"},
            {"text":"Purple (Munsell)","hex":"#9F00C5"},
            {"text":"Purple (X11)","hex":"#A020F0"},
            {"text":"Purple mountain majesty","hex":"#9678B6"},
            {"text":"Purple navy","hex":"#4E5180"},
            {"text":"Purple pizzazz","hex":"#FE4EDA"},
            {"text":"Purple Plum","hex":"#9C51B6"},
            {"text":"Purpureus","hex":"#9A4EAE"},
            {"text":"Queen blue","hex":"#436B95"},
            {"text":"Queen pink","hex":"#E8CCD7"},
            {"text":"Quick Silver","hex":"#A6A6A6"},
            {"text":"Quinacridone magenta","hex":"#8E3A59"},
            {"text":"Radical Red","hex":"#FF355E"},
            {"text":"Raisin black","hex":"#242124"},
            {"text":"Rajah","hex":"#FBAB60"},
            {"text":"Raspberry","hex":"#E30B5D"},
            {"text":"Raspberry glace","hex":"#915F6D"},
            {"text":"Raspberry rose","hex":"#B3446C"},
            {"text":"Raw Sienna","hex":"#D68A59"},
            {"text":"Raw umber","hex":"#826644"},
            {"text":"Razzle dazzle rose","hex":"#FF33CC"},
            {"text":"Razzmatazz","hex":"#E3256B"},
            {"text":"Razzmic Berry","hex":"#8D4E85"},
            {"text":"Rebecca Purple","hex":"#663399"},
            {"text":"Red","hex":"#FF0000"},
            {"text":"Red (Crayola)","hex":"#EE204D"},
            {"text":"Red (Munsell)","hex":"#F2003C"},
            {"text":"Red (NCS)","hex":"#C40233"},
            {"text":"Red (Pantone)","hex":"#ED2939"},
            {"text":"Red (pigment)","hex":"#ED1C24"},
            {"text":"Red (RYB)","hex":"#FE2712"},
            {"text":"Red-orange","hex":"#FF5349"},
            {"text":"Red-orange (Crayola)","hex":"#FF681F"},
            {"text":"Red-orange (Color wheel)","hex":"#FF4500"},
            {"text":"Red-purple","hex":"#E40078"},
            {"text":"Red Salsa","hex":"#FD3A4A"},
            {"text":"Red-violet","hex":"#C71585"},
            {"text":"Red-violet (Crayola)","hex":"#C0448F"},
            {"text":"Red-violet (Color wheel)","hex":"#922B3E"},
            {"text":"Redwood","hex":"#A45A52"},
            {"text":"Resolution blue","hex":"#002387"},
            {"text":"Rhythm","hex":"#777696"},
            {"text":"Rich black","hex":"#004040"},
            {"text":"Rich black (FOGRA29)","hex":"#010B13"},
            {"text":"Rich black (FOGRA39)","hex":"#010203"},
            {"text":"Rifle green","hex":"#444C38"},
            {"text":"Robin egg blue","hex":"#00CCCC"},
            {"text":"Rocket metallic","hex":"#8A7F80"},
            {"text":"Roman silver","hex":"#838996"},
            {"text":"Rose","hex":"#FF007F"},
            {"text":"Rose bonbon","hex":"#F9429E"},
            {"text":"Rose Dust","hex":"#9E5E6F"},
            {"text":"Rose ebony","hex":"#674846"},
            {"text":"Rose madder","hex":"#E32636"},
            {"text":"Rose pink","hex":"#FF66CC"},
            {"text":"Rose quartz","hex":"#AA98A9"},
            {"text":"Rose red","hex":"#C21E56"},
            {"text":"Rose taupe","hex":"#905D5D"},
            {"text":"Rose vale","hex":"#AB4E52"},
            {"text":"Rosewood","hex":"#65000B"},
            {"text":"Rosso corsa","hex":"#D40000"},
            {"text":"Rosy brown","hex":"#BC8F8F"},
            {"text":"Royal blue (dark)","hex":"#002366"},
            {"text":"Royal blue (light)","hex":"#4169E1"},
            {"text":"Royal purple","hex":"#7851A9"},
            {"text":"Royal yellow","hex":"#FADA5E"},
            {"text":"Ruber","hex":"#CE4676"},
            {"text":"Rubine red","hex":"#D10056"},
            {"text":"Ruby","hex":"#E0115F"},
            {"text":"Ruby red","hex":"#9B111E"},
            {"text":"Rufous","hex":"#A81C07"},
            {"text":"Russet","hex":"#80461B"},
            {"text":"Russian green","hex":"#679267"},
            {"text":"Russian violet","hex":"#32174D"},
            {"text":"Rust","hex":"#B7410E"},
            {"text":"Rusty red","hex":"#DA2C43"},
            {"text":"Sacramento State green","hex":"#043927"},
            {"text":"Saddle brown","hex":"#8B4513"},
            {"text":"Safety orange","hex":"#FF7800"},
            {"text":"Safety orange (blaze orange)","hex":"#FF6700"},
            {"text":"Safety yellow","hex":"#EED202"},
            {"text":"Saffron","hex":"#F4C430"},
            {"text":"Sage","hex":"#BCB88A"},
            {"text":"St. Patrick's blue","hex":"#23297A"},
            {"text":"Salmon","hex":"#FA8072"},
            {"text":"Salmon pink","hex":"#FF91A4"},
            {"text":"Sand","hex":"#C2B280"},
            {"text":"Sand dune","hex":"#967117"},
            {"text":"Sandy brown","hex":"#F4A460"},
            {"text":"Sap green","hex":"#507D2A"},
            {"text":"Sapphire","hex":"#0F52BA"},
            {"text":"Sapphire blue","hex":"#0067A5"},
            {"text":"Sapphire (Crayola)","hex":"#0067A5"},
            {"text":"Satin sheen gold","hex":"#CBA135"},
            {"text":"Scarlet","hex":"#FF2400"},
            {"text":"Schauss pink","hex":"#FF91AF"},
            {"text":"School bus yellow","hex":"#FFD800"},
            {"text":"Screamin' Green","hex":"#66FF66"},
            {"text":"Sea green","hex":"#2E8B57"},
            {"text":"Sea green (Crayola)","hex":"#00FFCD"},
            {"text":"Seal brown","hex":"#59260B"},
            {"text":"Seashell","hex":"#FFF5EE"},
            {"text":"Selective yellow","hex":"#FFBA00"},
            {"text":"Sepia","hex":"#704214"},
            {"text":"Shadow","hex":"#8A795D"},
            {"text":"Shadow blue","hex":"#778BA5"},
            {"text":"Shamrock green","hex":"#009E60"},
            {"text":"Sheen green","hex":"#8FD400"},
            {"text":"Shimmering Blush","hex":"#D98695"},
            {"text":"Shiny Shamrock","hex":"#5FA778"},
            {"text":"Shocking pink","hex":"#FC0FC0"},
            {"text":"Shocking pink (Crayola)","hex":"#FF6FFF"},
            {"text":"Sienna","hex":"#882D17"},
            {"text":"Silver","hex":"#C0C0C0"},
            {"text":"Silver (Crayola)","hex":"#C9C0BB"},
            {"text":"Silver (Metallic)","hex":"#AAA9AD"},
            {"text":"Silver chalice","hex":"#ACACAC"},
            {"text":"Silver pink","hex":"#C4AEAD"},
            {"text":"Silver sand","hex":"#BFC1C2"},
            {"text":"Sinopia","hex":"#CB410B"},
            {"text":"Sizzling Red","hex":"#FF3855"},
            {"text":"Sizzling Sunrise","hex":"#FFDB00"},
            {"text":"Skobeloff","hex":"#007474"},
            {"text":"Sky blue","hex":"#87CEEB"},
            {"text":"Sky blue (Crayola)","hex":"#76D7EA"},
            {"text":"Sky magenta","hex":"#CF71AF"},
            {"text":"Slate blue","hex":"#6A5ACD"},
            {"text":"Slate gray","hex":"#708090"},
            {"text":"Slimy green","hex":"#299617"},
            {"text":"Smitten","hex":"#C84186"},
            {"text":"Smoky black","hex":"#100C08"},
            {"text":"Snow","hex":"#FFFAFA"},
            {"text":"Solid pink","hex":"#893843"},
            {"text":"Sonic silver","hex":"#757575"},
            {"text":"Space cadet","hex":"#1D2951"},
            {"text":"Spanish bistre","hex":"#807532"},
            {"text":"Spanish blue","hex":"#0070B8"},
            {"text":"Spanish carmine","hex":"#D10047"},
            {"text":"Spanish gray","hex":"#989898"},
            {"text":"Spanish green","hex":"#009150"},
            {"text":"Spanish orange","hex":"#E86100"},
            {"text":"Spanish pink","hex":"#F7BFBE"},
            {"text":"Spanish red","hex":"#E60026"},
            {"text":"Spanish sky blue","hex":"#00FFFF"},
            {"text":"Spanish violet","hex":"#4C2882"},
            {"text":"Spanish viridian","hex":"#007F5C"},
            {"text":"Spring bud","hex":"#A7FC00"},
            {"text":"Spring Frost","hex":"#87FF2A"},
            {"text":"Spring green","hex":"#00FF7F"},
            {"text":"Spring green (Crayola)","hex":"#ECEBBD"},
            {"text":"Star command blue","hex":"#007BB8"},
            {"text":"Steel blue","hex":"#4682B4"},
            {"text":"Steel pink","hex":"#CC33CC"},
            {"text":"Steel Teal","hex":"#5F8A8B"},
            {"text":"Stil de grain yellow","hex":"#FADA5E"},
            {"text":"Straw","hex":"#E4D96F"},
            {"text":"Sugar Plum","hex":"#914E75"},
            {"text":"Sunglow","hex":"#FFCC33"},
            {"text":"Sunray","hex":"#E3AB57"},
            {"text":"Sunset","hex":"#FAD6A5"},
            {"text":"Super pink","hex":"#CF6BA9"},
            {"text":"Sweet Brown","hex":"#A83731"},
            {"text":"Tan","hex":"#D2B48C"},
            {"text":"Tan (Crayola)","hex":"#D99A6C"},
            {"text":"Tangerine","hex":"#F28500"},
            {"text":"Tango pink","hex":"#E4717A"},
            {"text":"Tart Orange","hex":"#FB4D46"},
            {"text":"Taupe","hex":"#483C32"},
            {"text":"Taupe gray","hex":"#8B8589"},
            {"text":"Tea green","hex":"#D0F0C0"},
            {"text":"Tea rose","hex":"#F88379"},
            {"text":"Tea rose","hex":"#F4C2C2"},
            {"text":"Teal","hex":"#008080"},
            {"text":"Teal blue","hex":"#367588"},
            {"text":"Telemagenta","hex":"#CF3476"},
            {"text":"Tenné (tawny)","hex":"#CD5700"},
            {"text":"Terra cotta","hex":"#E2725B"},
            {"text":"Thistle","hex":"#D8BFD8"},
            {"text":"Thulian pink","hex":"#DE6FA1"},
            {"text":"Tickle Me Pink","hex":"#FC89AC"},
            {"text":"Tiffany Blue","hex":"#0ABAB5"},
            {"text":"Timberwolf","hex":"#DBD7D2"},
            {"text":"Titanium yellow","hex":"#EEE600"},
            {"text":"Tomato","hex":"#FF6347"},
            {"text":"Tropical rain forest","hex":"#00755E"},
            {"text":"True Blue","hex":"#2D68C4"},
            {"text":"Trypan Blue","hex":"#1C05B3"},
            {"text":"Tufts blue","hex":"#3E8EDE"},
            {"text":"Tumbleweed","hex":"#DEAA88"},
            {"text":"Turquoise","hex":"#40E0D0"},
            {"text":"Turquoise blue","hex":"#00FFEF"},
            {"text":"Turquoise green","hex":"#A0D6B4"},
            {"text":"Turtle green","hex":"#8A9A5B"},
            {"text":"Tuscan","hex":"#FAD6A5"},
            {"text":"Tuscan brown","hex":"#6F4E37"},
            {"text":"Tuscan red","hex":"#7C4848"},
            {"text":"Tuscan tan","hex":"#A67B5B"},
            {"text":"Tuscany","hex":"#C09999"},
            {"text":"Twilight lavender","hex":"#8A496B"},
            {"text":"Tyrian purple","hex":"#66023C"},
            {"text":"UA blue","hex":"#0033AA"},
            {"text":"UA red","hex":"#D9004C"},
            {"text":"Ultramarine","hex":"#3F00FF"},
            {"text":"Ultramarine blue","hex":"#4166F5"},
            {"text":"Ultra pink","hex":"#FF6FFF"},
            {"text":"Ultra red","hex":"#FC6C85"},
            {"text":"Umber","hex":"#635147"},
            {"text":"Unbleached silk","hex":"#FFDDCA"},
            {"text":"United Nations blue","hex":"#5B92E5"},
            {"text":"Unmellow yellow","hex":"#FFFF66"},
            {"text":"UP Forest green","hex":"#014421"},
            {"text":"UP maroon","hex":"#7B1113"},
            {"text":"Upsdell red","hex":"#AE2029"},
            {"text":"Uranian blue","hex":"#AFDBF5"},
            {"text":"USAFA blue","hex":"#004F98"},
            {"text":"Van Dyke brown","hex":"#664228"},
            {"text":"Vanilla","hex":"#F3E5AB"},
            {"text":"Vanilla ice","hex":"#F38FA9"},
            {"text":"Vegas gold","hex":"#C5B358"},
            {"text":"Venetian red","hex":"#C80815"},
            {"text":"Verdigris","hex":"#43B3AE"},
            {"text":"Vermilion","hex":"#E34234"},
            {"text":"Vermilion","hex":"#D9381E"},
            {"text":"Veronica","hex":"#A020F0"},
            {"text":"Violet","hex":"#8F00FF"},
            {"text":"Violet (color wheel)","hex":"#7F00FF"},
            {"text":"Violet (crayola)","hex":"#963D7F"},
            {"text":"Violet (RYB)","hex":"#8601AF"},
            {"text":"Violet (web)","hex":"#EE82EE"},
            {"text":"Violet-blue","hex":"#324AB2"},
            {"text":"Violet-blue (Crayola)","hex":"#766EC8"},
            {"text":"Violet-red","hex":"#F75394"},
            {"text":"Viridian","hex":"#40826D"},
            {"text":"Viridian green","hex":"#009698"},
            {"text":"Vivid burgundy","hex":"#9F1D35"},
            {"text":"Vivid sky blue","hex":"#00CCFF"},
            {"text":"Vivid tangerine","hex":"#FFA089"},
            {"text":"Vivid violet","hex":"#9F00FF"},
            {"text":"Volt","hex":"#CEFF00"},
            {"text":"Warm black","hex":"#004242"},
            {"text":"Wheat","hex":"#F5DEB3"},
            {"text":"White","hex":"#FFFFFF"},
            {"text":"Wild blue yonder","hex":"#A2ADD0"},
            {"text":"Wild orchid","hex":"#D470A2"},
            {"text":"Wild Strawberry","hex":"#FF43A4"},
            {"text":"Wild watermelon","hex":"#FC6C85"},
            {"text":"Windsor tan","hex":"#A75502"},
            {"text":"Wine","hex":"#722F37"},
            {"text":"Wine dregs","hex":"#673147"},
            {"text":"Winter Sky","hex":"#FF007C"},
            {"text":"Wintergreen Dream","hex":"#56887D"},
            {"text":"Wisteria","hex":"#C9A0DC"},
            {"text":"Wood brown","hex":"#C19A6B"},
            {"text":"Xanthic","hex":"#EEED09"},
            {"text":"Xanadu","hex":"#738678"},
            {"text":"Xiketic","hex":"#0C020F"},
            {"text":"Yale Blue","hex":"#0F4D92"},
            {"text":"Yellow","hex":"#FFFF00"},
            {"text":"Yellow (Crayola)","hex":"#FCE883"},
            {"text":"Yellow (Munsell)","hex":"#EFCC00"},
            {"text":"Yellow (NCS)","hex":"#FFD300"},
            {"text":"Yellow (Pantone)","hex":"#FEDF00"},
            {"text":"Yellow (process)","hex":"#FFEF00"},
            {"text":"Yellow (RYB)","hex":"#FEFE33"},
            {"text":"Yellow-green","hex":"#9ACD32"},
            {"text":"Yellow-green (Crayola)","hex":"#C5E384"},
            {"text":"Yellow-green (Color Wheel)","hex":"#30B21A"},
            {"text":"Yellow Orange","hex":"#FFAE42"},
            {"text":"Yellow Orange (Color Wheel)","hex":"#FF9505"},
            {"text":"Yellow Sunshine","hex":"#FFF700"},
            {"text":"YInMn Blue","hex":"#2E5090"},
            {"text":"Zaffre","hex":"#0014A8"},
            {"text":"Zomp","hex":"#39A78E"}
        ]
    }
    }
    render(){
        const colors = this.state.colors;
       // var colors = ['Jake', 'Jon', 'Thruster'];
        return (
            <ul>
            {colors.map(function(color, index){
                var divStyle = {
                    backgroundColor: color.hex
                }
                return <li key={ index } style={divStyle}>{color.text}</li>;
              })}
            </ul>
        )
    }
}